### ISSUE TITLE
Email question

### ISSUE THREAD

**Issue by racitup** [olihawkins/pdpy#1]
Hi Oli, great work!
Sorry if you'd rather this be asked elsewhere, but how would I go about getting a list of email addresses? I have used fetch_mps to get the list of MPs I want, but there isn't an email address.
I suspect I need to do a further query against the individual person_id url, but can't seem to find it..
Code:
```
#!/usr/bin/env python
import pdpy

def get_mps():
    mps = pdpy.fetch_mps(on_date='2019-03-29')
    fields = mps.keys()
    gen_dict = (dict(zip(fields, mp)) for mp in mps.values)
    gen_filter = ({k:mp[k] for k in mp.keys() if k in ['full_title', 'person_id', 'date_of_birth']} for mp in gen_dict)
    for mp in gen_filter:
        yield mp
```

**Comment by olihawkins** [comment]
Hi racitup,

Yes, Members' email addresses aren't included in the predefined queries in the package. You need to build a new SPARQL query that asks for that data and sends it to the platform with `sparql_select`. The example code in this gist shows you how to get parliamentary email addresses for all MPs (or Lords). You can then filter the results using the person ids from your `fetch_mps` call to find the email addresses of the MPs you are interested in.

https://gist.github.com/olihawkins/99044b7ece130a1af3bfd8a0b01dd56f

Bear in mind that this example query will return more than one row per MP if they have more than one email address. You might want to think about using pandas to filter and subset the data in the results from pdpy as it makes it easier to handle the tabular data (e.g. for selecting only some of the columns, or only the rows that meet certain criteria).

**Comment by racitup** [comment]
Hi Oli,

Thanks for doing that but it does look like a complicated query. It's the first time I've run into sparql and pandas, though pandas looks useful to keep in mind.
In the end I parsed one of the XML documents from MNIS in JS:
https://jsfiddle.net/racitup/ebafu3dx/

Are you planning to expand the pdpy API to something like the additional data output interface of MNIS?

**Comment by olihawkins** [comment]
I do hope to expand the higher level API in pdpy/pdpr in future, time permitting. But the lower level API is very powerful if you can get your head around SPARQL (which also opens up the universe of Wikidata). MNIS has some oddities which make me wary of relying on it (e.g. the [endpoint](http://data.parliament.uk/membersdataplatform/services/mnis/members/query/House=Commons%7CMembership=all%7Cid=1571/GovernmentPosts%7COppositionPosts/) that is supposed to give you all government posts a Member has held only returns their current posts). Pandas is very cool and makes it very easy to manipulate tabular data in Python. The pdpy and pdpr packages are designed primarily with data analysis in mind and pandas is the most commonly used data analysis framework for Python.

**Comment by racitup** [comment]
Out of interest, is there a way of searching for House of Commons vote results if I know the date and division number and linking it to the contact details?
You don't have to actually do it, but a link to some documentation to how I might form a sparql query would be great!

**Comment by racitup** [comment]
It's okay, I think I figured it out: https://api.parliament.uk/sparql & https://query.wikidata.org/
